# Site settings
title: Joana Neto
email: joana.b.neto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Website of Joana Neto
baseurl: "" # the subpath of your site, e.g. /blog
url: "//joanabneto.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown